version: "3.9"

services:
  frontend:
    build: ./client
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env   
    stdin_open: true
    tty: true

  backend:
    build: ./fastapi
    ports:
      - "8000:8000"
    env_file:
      - ./fastapi/.env     
